### ISSUE TITLE
How to find out if match is exhaustive

### ISSUE THREAD

**Issue by barsdeveloper** [francisrstokes/arcsecond#106]
When running the method run on a rule, it will parse up until a certain point without error, but if there is more text to parse, how to determine if the parsing was exhaustive (if it consumed the whole input)? Fork has the same problem.
Apparently there is not easy way to do it, I've tried to to compare the string length of the input against result.index but they do differ in case of non ascii characters. Any idea?

**Comment by francisrstokes** [comment]
Hi,

What you're looking for is the [`endOfInput`](https://github.com/francisrstokes/arcsecond#endofinput) parser.

**Comment by barsdeveloper** [comment]
The problem with this approach is that you can't then parse using intermediate rules.

**Comment by francisrstokes** [comment]
I'm not entirely sure what you mean. If your top level parser has an endOfInput as part it's matching sequence, it will succeed, otherwise parsing fails. Any intermediate steps would have already been parsed and processed.
If you're trying to make decisions in individual parsers about how to proceed if the end of input is reached, you can look into using the chain methid, or decide.
I don't know if you've taken a look through the tutorial docs, but it might help you figure out the idiomatic ways to approach this kind of thing in arcsecond. I'm not too familiar with parsimmon, but I know there are a few conceptual differences to parser construction.

**Comment by barsdeveloper** [comment]
Imagine you have a common grammar in your program, let's say this grammar
https://github.com/francisrstokes/arcsecond/blob/main/examples/json/json.js
You have different rules and you decide to use some of them to parse, in some parts of your application some text.
Sometimes you want to parse an entire json and you will use parseJsonValue. But sometimes maybe you want to parse just a small fragment like let's say parseNull. Now you give it instead of the text "null", "nullable" which has a different meaning in the context of your application. The parse will succeed.
If instead after null the parseNull expects endOfInput then it can't be used to compose other parsers, you would need an additional concepts which is the "null" fragment making the need to have double rules for everything.

Ideally this should be solved at the level of Parser class (or whatever that type is in typescrip). I would introduce a method called "parse" that uses run and expects end of input.

Work around I'm using for now (maybe someone is interested), it works in case of non ascii characters as well.
```Javascript
    /**
     * @template T
     * @param {Parser<T>} parser
     * @param {String} value
     */
    static parse(parser, value) {
        let errorMessage = "Error when trying to parse..."
        return parser.fork(
            value,
            msg => {
                throw new Error(errorMessage)
            },
            (result, state) => {
                if (state.index < state.dataView.byteLength) {
                    throw new Error(errorMessage)
                }
                return result
            }
        )
    }
```
