### ISSUE TITLE
Cannot use sepBy in the first item of choice

### ISSUE THREAD

**Issue by jeffrose** [francisrstokes/arcsecond#19]
I've found that using `sepBy` in the first item of `choice` causes parsing issues.

This code fails...
```javascript
const
    commaSeparated = sepBy( char( ',' ) ),
    betweenBraces = between( char( '{' ) )( char( '}' ) ),
    list = commaSeparated( digits ),
    range = sequenceOf( [ digits, str( '..' ), digits ] );
export const brace = betweenBraces( choice( [ list, range ] ) );
brace.run( '{0..9}' ); // ERROR
brace.run( '{1,2,3,4}' ); // ['1', '2', '3', '4']
```
... however this code works...
```javascript
const
    commaSeparated = sepBy( char( ',' ) ),
    betweenBraces = between( char( '{' ) )( char( '}' ) ),
    list = commaSeparated( digits ),
    range = sequenceOf( [ digits, str( '..' ), digits ] );
export const brace = betweenBraces( choice( [ range, list ] ) );
brace.run( '{0..9}' ); // ['0', '..', '9']
brace.run( '{1,2,3,4}' );  // ['1', '2', '3', '4']
```
Is this expected behavior?

**Comment by francisrstokes** [comment]
Hey Jeff,

This is indeed expected behavior. `sepBy` is a parser that matches _zero or more times_ - in other words it never actually fails. It will always return an empty array if it can't match anything. It has a counter part - `sepBy1` - that matches _one or more times_, which you could use as the first parser in a choice.

You can think of `sepBy` as `possibly(sepBy1).map(x => x === null ? [] : x)`.

**Comment by jeffrose** [comment]
At least in the example by provided, `sepBy1` does not resolve the problem. You actually get the same parsing error that you get with `sepBy`.

```
const
    commaSeparated = sepBy1( char( ',' ) ),
    betweenBraces = between( char( '{' ) )( char( '}' ) ),
    list = commaSeparated( digits ),
    range = sequenceOf( [ digits, str( '..' ), digits ] );
export const brace = betweenBraces( choice( [ list, range ] ) );
brace.run( '{0..9}' ); // ERROR
brace.run( '{1,2,3,4}' ); // ['1', '2', '3', '4']
```

Doesn't this also imply you could only have one `sepBy` in a `choice` ever? If that's an expected limitation, it should be called out in some way in the documentation as possibly in code as well as an error.

**Comment by francisrstokes** [comment]
Ah now I see your problem.
`sepBy` and `sepBy1` will both happily capture a single item. You'd need to write a stricter `sepBy` that needs at least 2 items (which implies it caught at least one separator).

This can be easily accomplished with chain:

```javascript
const sepBy2 = separator => value => sepBy1(separator)(value).chain(results => {
  if (results.length < 2) {
    return fail('Failed to capture at least 2 elements');
  }
  return succeedWith(results);
});
```

I tested it with you code and it works.

> Doesn't this also imply you could only have one sepBy in a choice ever?

Yes it does. More than that, it implies you could only ever have one *zero or more*-matching parser in a choice.

> it should be called out in some way in the documentation

That's a fair point. Can I ask where you'd expect to see that in the docs? Because it's more about the nature of parser combinators than it is specifically about sepBy/many/choice/whatever.

**Comment by jeffrose** [comment]
I would expect to see called out in `choice` as note or warning of some sort. I think the hard part is making it clear to newcomers, which methods are affected.

> it implies you could only ever have one _zero or more_-matching parser in a choice.

The category of _zero or more_-matching may be accurate but not clearly understood at first. At the very least methods like `sepBy` should be labeled as such so I can track down the information.

If it's possible to detect in code, a more specific parsing error would be helpful too.

You may want to consider a `sepByN` method where you can specify the number instead of just `sepBy1`.
