### ISSUE TITLE
Suggestion: Variadic arguments

### ISSUE THREAD

**Issue by poteat** [francisrstokes/arcsecond#44]
It would arguably slightly improve the external ergonomics of this library if functions that take in only one parameter, which must be an array, had a second variadic type signature, so the brackets could be dropped.

In this case, `A.sequenceOf` would optionally take in a variadic number of arguments to construct its sequence.

**Comment by francisrstokes** [comment]
There are two main reasons why I wouldn't want to do this in arcsecond.

I'm not a big fan of variadic type signatures (especially in a language without proper support for overloading). The array works here because it encodes the sequencing and inclusion of every element. You can store that separately, compute it, process it - all as an entity, separate from the idea of `sequenceOf`.

Actually, in general, I'm not so militantly against variadic signatures - but in this case it wouldn't really be in keeping with the philosophy of this library. Every function in arcsecond takes exactly one argument (because they're curried). Allowing more arguments would break that fundamental assumption.

Now, all of that said, you could very easily create an adapter in your own projects:

```javascript
const variadify = parserFn => (...args) => parserFn(args);
const variadifyAll = A => Object.entries(A).reduce((newA, [key, parserFn]) => {
  if (typeof parserFn === 'function') {
    newA[key] = variadify(parserFn);
  } else {
    newA[key] = parserFn;
  }
  return newA;
}, {});
```

Then you could use it something like

```javascript
const A = require('arcsecond');
const V = variadifyAll(A);

const someSequence = V.sequenceOf(
  A.str('hello'),
  A.whitespace,
  A.str('world')
);
```
