### ISSUE TITLE
Range Errors

### ISSUE THREAD

**Issue by jeffrose** [francisrstokes/arcsecond#51]
Since upgrading to Arcsecond 3.x, I am seeing range errors popup in my local development. Here's an example, redacted for brevity...

```
RangeError: Offset is outside the bounds of the DataView at ... /arcsecond/index.mjs:57:1 <- ...

RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
...
```

While these errors are the result of me mis-using a parser, it would be nice if they were caught and a more helpful error thrown.

I'll see if I can come up with some simple reproduction steps but doing some range checks or try-catches might help bulletproof the code.

**Comment by francisrstokes** [comment]
Agreed - without looking deeply into it right now I assume it's to do with the unicode parsing - since that can read a variable number of bytes depending on an input byte. Would be awesome if you could provide a full stack trace for one/some of the errors, but I'll be taking a look into it anyway 👍 Thanks Jeff!

**Comment by francisrstokes** [comment]
I opened #52 - which I'm hoping is going to fix the issue, but I'd like to add a few real world regression tests, in order to make sure the problems you're encountering don't pop up again.

**Comment by jeffrose** [comment]
The parser I was getting the error in was fairly complex and still in development. I will try to pare it down to a testable use case.

**Comment by francisrstokes** [comment]
OK no worries. I came up with this, which crashes out before the fix is applied:

```javascript
anyChar.run(new Uint8Array([0b11110000]));
// -> RangeError: Offset is outside the bounds of the DataView
```

Because it's looking for a `utf8` character, and those first four bits signify that there are 4 bytes in this character, it was happily reading off the end of the buffer. The new changes produce an "unexpected end of input" parse error instead.

Same would happen for:

- `char`
- `digit`
- `letter`
- `anyOfString`
- `anyCharExcept`

Let's see if this fix takes care of your issue, and otherwise feel free to open another!

**Comment by francisrstokes** [comment]
Release in 3.1.1
