### ISSUE TITLE
Parsers sometimes never terminate? Infinite loop?

### ISSUE THREAD

**Issue by justgage** [francisrstokes/arcsecond#8]
I ran into a situation where this will never terminate. Maybe I'm doing something wrong? Liked your medium article BTW. 

```js
const {
  str,
  sequenceOf,
  choice,
  char,
  parse,
  letters,
  everythingUntil,
  many,
  whitespace,
} = require('arcsecond');


const boldParser =
    sequenceOf([
      char("*"),
      everythingUntil(char("*")),
      char("*"),
    ])

const fullParser = many(
  choice(
    [
      letters,
      whitespace
    ]
  )
)

// Create a function that can take a string and run our parser
const parsemd = parse(fullParser);

console.log(parsemd('We love *to parse* _things_').value)
```

**Comment by francisrstokes** [comment]
Hey @justgage, Thanks for the nice words!

You've come across a tricky one here - the reason your parser doesn't terminate is because the `whitespace` parser matches *zero or more* characters, meaning it technically never fails. So if you have a `many(choice([...]))` that contains a `whitespace`, it's always going to "match" something, only that match doesn't move the parser along and so is always going to get stuck.

The solution would be to build a non-optional whitespace parser like this (although there are other ways):

```javascript
// Ensure we get at least one whitespace character
const nonOptionalWhitespace = regex(/^[ \n\t\r]+/);


const fullParser = many(
  choice(
    [
      letters,
      nonOptionalWhitespace
    ]
  )
)
```

Then the parser should succeed up until `We love `.

Hope this helps!

**Comment by justgage** [comment]
Ah good to know, I do feel that perhaps a better design would be for whitespace to match just one then use other utilities to repeat it. Or is the `many` the thing that does zero or more?

**Comment by francisrstokes** [comment]
It's both. `many` and `whitespace` both match zero or more times, which is exactly why they can't be used together. Any combination like that will result in an infinite loop. I do agree that maybe the name `whitespace` suggests  that it could be a one or more parser - my original thinking was for implementing optional whitespace in programming languages or formats like JSON. 

Action wise, I think the best remedy with the least impact (in terms of deprecation and meaning change) is to add a `nonOptionalWhitespace` parser to the library in a minor version.

**Comment by justgage** [comment]
Yeah that makes sense. Anyway I think my issue is solved, thanks for your time!
