### ISSUE TITLE
Using promises and async await

### ISSUE THREAD

**Issue by vwkd** [francisrstokes/arcsecond#86]
Could arcsecond use async functions instead of generators and promises by default?

My guess is besides requiring deep changes to the library this would also make the “simple parser” approach impossible. This might be a trade off for very simple parsers, but might be worth it considering most users will likely want to go beyond a hello world example.

A single coroutine approach could help clarity, accelerate learning, and also make debugging easy by default.

Maybe a thing to consider for the next major version.

**Comment by francisrstokes** [comment]
Hi @vwkd - thanks for the question. I'm afraid that for better or worse, this approach wouldn't work. Generators are used because they provide a low-level mechanism to build mini _program/interpreter_ pairs. The generator function allows the user to specify the "special" points in the function with `yield` (the "program"), while the `coroutine` function itself takes this program, and _interprets_ it to create a parser. I've made a few videos about generators, so if you want a bit more detail you can check [this](https://www.youtube.com/watch?v=yPEwjpIWOGg) one and [these two](https://www.youtube.com/playlist?list=PLP29wDx6QmW7IaD762Rf_Awfr1Wxz0Amq).

To be concrete, generators a lower-level, and more powerful mechanism, than async functions. You can make async functions out of generators, but you can't make generators out of async functions.
