### ISSUE TITLE
Using previous value and variable repetition

### ISSUE THREAD

**Issue by vwkd** [francisrstokes/arcsecond#87]
Does arcsecond allow to implement a sequence of variable repetition, in which the next value depends on the previous value?

A simple example is a list of increasing integers `12345…`. A character is the previous one (coerced to a number) plus one.

I know I can use `decide` or `.chain` for a single decision. I also know I can use `many` for variable repetition. But how can I combine them?

I could imagine `many` taking a function that receives the previous value as argument and can return a parser depending on that. The above example using pseudo-code

```js
many( last => char(Number(last) + 1) )
```

Am I missing something? Is this already possible in arcsecond?

------

I tried using a coroutine and a loop, but couldn’t get it to work.

```js
coroutine( function* () {
  const results = [];

  for (let i = 1; ;i += 1) {
    const maybe = yield possibly( char(`${i}`) );

    if (maybe.result === null) {
      break;
    } else {
      results.push(maybe);
    }
  }
  
  return results;
})
```

**Comment by francisrstokes** [comment]
Something like this should work:

```javascript
const {coroutine, possibly, char} = require('arcsecond');

const dependantMany = nextParserFn => prevResult => coroutine(function* () {
    let results = [prevResult];
    let currentPrevResult = prevResult;

    while (true) {
        const result = yield possibly(nextParserFn(currentPrevResult));
        if (result === null) {
            // We're done
            return results;
        }
        results.push(result);
        currentPrevResult = result;
    }
});

const input = '1234568';
const parser = char('1').chain(dependantMany(x => {
    const next = (Number(x) + 1).toString();
    return char(next);
}));

const result = parser.run(input);
console.log(result);
```

I'm not sure about typescript types for now - you'd need to make `dependantMany` generic, and maybe lose the curried function.

**Comment by francisrstokes** [comment]
(The result would be:)

```javascript
{
  isError: false,
  result: [ '1', '2', '3', '4', '5', '6' ],
  index: 6,
  data: null
}
```

**Comment by francisrstokes** [comment]
Looking at your code, you were almost there, only you used `possibly` incorrectly. You were using it a little more like `either` (https://github.com/francisrstokes/arcsecond#either), which could be used in place of possibly if you ever expected `null` to be a real value the parser could return.

**Comment by vwkd** [comment]
Thank you, that’s really helpful! Great to know arcsecond supports it and I was indeed on the right track with a coroutine and a loop and only confused the return value from a parser and the return value when executing it, which lead me to mistakenly check for a `result` (or `isError`) property on the parser return value.

(The plethora of possibilities are a bit confusing - when to use instance methods or functions, `.chain` or `decide`, a `coroutine` or a `pipedParser`, do I need internal state or can I pass the value along the pipe, how can I access internal state without an instance method, etc. But I’m sure one can get familiar with more time.)

Thanks for helping out!

**Comment by francisrstokes** [comment]
> The plethora of possibilities are a bit confusing

That's a fair point. The library supports multiple styles of programming. Some people like to use pipes and sequences to express parsers in a point-free way (more towards haskell), and others prefer to write more imperative style parsers with coroutine. There are also some subtle differences between things like `decide` and `.chain` which might lead you to use one or the other. For example, `.chain` is really a *transformation* of the result into the next parser - meaning if you actually want to keep that result around, you have to do some extra work to save it (see above where I place the result into the results array).

```javascript
// This parser "loses" the value 'a'
letter.chain(l => l === 'a' ? digit : letter);

// This parser keeps 'a' around
sequenceOf([
  letter,
  decide(l => l === 'a' ? digit : letter)
]);

// This parser keeps 'a' around with some extra work
letter.chain(l => (l === 'a' ? digit : letter).map(nextResult => [l, nextResult]));
```

Something to keep in mind is that `coroutine` is basically the most powerful construct in the library - every yield is essentially a `.chain` in a sequence where you choose how to proceed based on the next value. As you mentioned before, there can be more straightforward ways to express simple ideas, but for more complex parsers (usually combinators that are more general utilities), it's the better way to go.

Really you just need to play around with it, because there is always more than one way to accomplish the goal. In the most extreme cases you can even drop down to writing a parser using the `Parser` constructor, but that is not documented because I want the option to break it between major versions if I choose 😄
