### ISSUE TITLE
Wrong index for some Unicode characters

### ISSUE THREAD

**Issue by vwkd** [francisrstokes/arcsecond#95]
Arcsecond counts a higher index than JavaScript for some Unicode characters.

I noticed this when trying to find an error and the index was too high.

Here’s minimal example using Georgian characters.

```js
const input = "დე";
console.log(input.length);
sequenceOf([str("დ"), str("ა")]).fork(input, console.log, console.log);
```

The parse error reports `index: 3` while the expected error is `index: 1` since the whole string is only `2` long.

It seems arcsecond counts triple the length for some Unicode characters compared to JavaScript.

I’m not sure what other Unicode characters are affected.

arcsecond@v4.1.0

**Comment by francisrstokes** [comment]
Hey @vwkd, thanks for opening the issue.

Arcsecond parses an equivalent UTF-8 stream from an input which is (in most cases) made up of code points. A code point can contain fewer bytes than an equivalent UTF-8 stream. In the example you shared:

`დე` is made up of the codepoints: `10d3 10d4`. But the UTF-8 stream is: `e1 83 93 e1 83 94`. The internal index keeps track of bytes, because that is what arcsecond parses (not codepoints), and therefore when you see index 3, it is actually correct.

I hope this makes some sense. If you're working with unicode, you can use the TextEncoder/TextDecoder APIs to go back and forward between bytes and code points.

**Comment by vwkd** [comment]
Thanks for the detailed explanation! Great to hear that this is indeed expected behavior. Though maybe it would be helpful to mention this in the documentation somewhere.

For anyone else wondering how to convert a byte index into a code point index, taking the length of the string-decoded first half of the byte array worked for me.

```js
const encoder = new TextEncoder();
const decoder = new TextDecoder();

const input = encoder.encode("დე");
const parser = sequenceOf([str("დ"), str("ა")]);

parser.fork(input, (error, parsingState) => {
  const inputBefore = input.slice(0, parsingState.index);
  const indexCodePoint = decoder.decode(inputBefore).length;
  
  console.error(error.replace(/(?<=position )\d+/, indexCodePoint));
}, console.log);
```

**Comment by francisrstokes** [comment]
Documentation improvement would definitely help here indeed. Your example is also really helpful, and would be a useful addition to the docs. I do see now, though, that it might be worth exposing the internal input buffer so that a user wouldn't need to re-encode their input. I'm not sure what the best way to do that would be, but perhaps the result type should be a little more advanced, and include some methods for doing these kinds of calculations in a more intuitive way. I'll have to think about that for a little while. I'll open a new issue for unicode docs and reference this one.
