### ISSUE TITLE
`sepBy1` errors if following parser is same separator

### ISSUE THREAD

**Issue by vwkd** [francisrstokes/arcsecond#98]
I have a variable-length sequence of tokens ending in a different token separated by the same separator. For example, a list of words ending in a number separated by space.

Here's a minimal example using `many`.

```js
const parser = sequenceOf([
  sequenceOf([
    letters,
    many(sequenceOf([
      char(" "),
      letters
    ])),
  ]),
  char(" "),
  digits,
]);

parser.fork("lorem 42", console.error, console.log);
parser.fork("lorem ipsum 42", console.error, console.log);
```

I like to make the code shorter using `sepBy1`. This should parse the same input (but not give the same result value, but that’s not the focus here).

```js
const parser = sequenceOf([
  sepBy1( char(" ")) (letters),
  char(" "),
  digits,
]);

parser.fork("lorem 42", console.error, console.log);
// ParseError (position 6): Expecting letters
parser.fork("lorem ipsum 42", console.error, console.log);
// ParseError (position 12): Expecting letters
```

However, this errors at the digit. It seems as the number part starts with the same separator, `sepBy1` tries and fails to parse the number, and doesn’t let the following parser try.

Is this a bug in arcsecond? At least this makes `sepBy1` not equivalent anymore to using `many` like above, which is _very_ unintuitive.

**Comment by francisrstokes** [comment]
Hey @vwkd - you're exposing all of the weird edges of the library :smile: I love it haha

So this is another case of, weirdly enough, expected behaviour. Here is a previous issue discussing it: https://github.com/francisrstokes/arcsecond/issues/26

But in short, `sepBy` and `sepBy1` are both combinators that collect values separated by a particular parser. So if a separator is encountered, then it expects another value. The solution is to either use something like you originally proposed, or alternatively, to use something like I shared in the other issue. Note that if you're using 5.x, you'll need to adapt the coroutine from the old generator style to the newer function based style.

**Comment by francisrstokes** [comment]
Oh and though I probably mentioned it in the other issue, the reason it is this way is because I based it on the `sepBy` implementations in Parsec. I thought it would be weird to deviate from the library I was taking inspiration from. I should probably just add another function to the library for this use case. Do you have any idea of a good name for such a function?

**Comment by vwkd** [comment]
Sorry for the duplicate issue! It took me so long to debug this that I missed to check for previous issues… 🥲

In this case, I’d vote to make a breaking change with a new major version to change any weird behavior to expected behavior (`sepBy` and any other “weird edges”). 

Creating another `sepByFixed` whose only difference is non-weird behavior would just add confusion, create more barriers to entry for learners, and increase size and maintenance burden.

If the current behavior bites people so harshly, also shown by the previous issue,  maybe it’s worth deviating from the inspiration. At the bare minimum there should be a big red warning in the documentation.

**Comment by vwkd** [comment]
Hopefully arcsecond fixes `sepBy1` in the next major version to give the expected behavior.

For the meantime, the following should work as a polyfill.

```js
const sepBy1 = separator => value => sequenceOf([
  value,
  many(sequenceOf([
    separator,
    value
  ]).map(a => a[1])),
]).map(([e, r]) => [e, ...r]);

const sepBy = separator => value => possibly(sepBy1(separator)(value)).map(a => a ?? [])
```

**Comment by francisrstokes** [comment]
No worries about the duplicate issue! It's always useful when there is something to refer back to.

The only problem with "fixing" the expected behaviour is that *expected behaviour* can change depending on what you're trying to accomplish. It is perfectly valid to assume that if you get a separator but no final value, then something is wrong with the input. You can't draw the conclusion that most people expect another behaviour from 2 issues (there could easily be 10000 cases of people experiencing their own expected behaviour, and never opening an issue because it just works 😄)

In any case, arcsecond was designed to flexible enough that a user could always create their own implementations from other primitives if needed, which is what you're doing now. I will put some thought into adding alternate versions to the library,I would rather not remove the existing ones with so little to go on

**Comment by vwkd** [comment]
Irrespective of deciding which behavior is “right”, everyone seems to agree that documenting it would be helpful. So maybe that could be a good start for tackling the “weird edges” of arcsecond.

**Comment by francisrstokes** [comment]
The documentation, as it stands now, does describe the behaviour:

> sepBy takes two parsers - a separator parser and a value parser - and returns a new parser that matches zero or more values from the value parser that are separated by values of the separator parser.

Perhaps the description is too succinct, but it *is* described. I think adding issue #99, and calling out the alternate versions in each parsers documentation would probably help highlight the confusion better than anything else.
